const mongoose = require("mongoose");

const productSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      required: true,
    },
    price: {
      type: Number,
      required: true,
    },
    discountPrice: {
      type: Number,
    },
    countInStock: {
      type: Number,
      required: true,
      default: 0,
    },
    sku: {
      type: String,
      unique: true,
      required: true,
    },
    category: {
      type: String,
      required: true,
    },
    brand: {
      type: String,
    },
    sizes: {
      type: [String],
      required: true,
    },
    colors: {
      type: [String],
      required: true,
    },
    collections: {
      type: String,
      required: true,
    },
    material: {
      type: String,
    },
    gender: {
      type: String,
      enum: ["Men", "Women", "Unisex"],
    },
    images: [
      {
        url: {
          type: String,
          required: true,
        },
        altText: {
          type: String,
        },
      },
    ],
    isFeatured: {
      type: Boolean,
      default: false,
    },
    isPublished: {
      type: Boolean,
      default: false,
    },
    rating: {
      type: Number,
      default: 0,
    },
    numReviews: {
      type: Number,
      default: 0,
    },
    tags: [String],
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    metaTitle: {
      type: String,
    },
    metaDescription: {
      type: String,
    },
    metaKeywords: {
      type: String,
    },
    dimensions: {
      length: Number,
      width: Number,
      height: Number,
    },
    weight: Number,
  },
  { timestamps: true },
);

module.exports = mongoose.model("Product", productSchema);

// <=============================== Product Schema ===============================>
//
// | Field Name      | Type               | Constraints/Description
// |-----------------|--------------------|----------------------------------------
// | ObjectId        | ObjectId           | Auto-generated by MongoDB
// | name            | String             | Required, trimmed
// | description     | String             | Required
// | price           | Number             | Required
// | discountPrice   | Number             | Optional
// | countInStock    | Number             | Required, default: 0
// | sku             | String             | Required, unique
// | category        | String             | Required
// | brand           | String             | Optional
// | sizes           | [String]           | Required, example: ['S', 'M', 'L']
// | colors          | [String]           | Required, example: ['Red', 'Blue']
// | collections     | String             | Required, example: 'Summer collection'
// | material        | String             | Optional
// | gender          | String             | Enum: ['Men', 'Women', 'Unisex']
// | images          | Array of Objects   | Required, each object contains:
// |                 |                    |   - url: String (required),
// |                 |                    |   - altText: String (optional)
// | isFeatured      | Boolean            | Default: false
// | isPublished     | Boolean            | Default: false
// | rating          | Number             | Default: 0
// | numReviews      | Number             | Default: 0
// | tags            | [String]           | Optional
// | user            | ObjectId           | Reference to User, required
// | metaTitle       | String             | Optional
// | metaDescription | String             | Optional
// | metaKeywords    | String             | Optional
// | dimensions      | Object             | Optional, contains:
// |                 |                    |   - length: Number,
// |                 |                    |   - width: Number,
// |                 |                    |   - height: Number
// | weight          | Number             | Optional
// | createdAt       | Date               | Auto-generated by timestamps
// | updatedAt       | Date               | Auto-updated by timestamps
